title: VidyaVantage
description: "From Grade 9 to Global PhD"
theme: jekyll-theme-cayman
favicon: /assets/images/favicon.ico
plugins:
  - jekyll-seo-tag

# ---------------------------------------------------
# CRITICAL SETTINGS FOR REPO: vidyavantage.github.io
# ---------------------------------------------------
url: "https://antoniovn96.github.io"
baseurl: "/vidyavantage.github.io" 
# ^ This matches your repository name exactly. 

css: "/assets/css/style.css"
