title: VidyaVantage
description: "From Grade 9 to Global PhD"
theme: jekyll-theme-cayman
favicon: /assets/images/favicon.ico
plugins:
  - jekyll-seo-tag

# ---------------------------------------------------
# CRITICAL FIX FOR YOUR LINKS
# ---------------------------------------------------
url: "https://antoniovn96.github.io"
baseurl: "/vidyavantage.github.io"

# Link to your custom CSS (Using relative_url is handled by the theme usually, 
# but this helps define the path)
css: "/assets/css/style.css"